version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: order-postgres
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - order_pg_data:/var/lib/postgresql/data

volumes:
  order_pg_data: